- name: Create All RoboShop Parameters
  hosts: localhost
  tasks:
    - name: Create Value
      community.aws.aws_ssm_parameter_store:
        name: "{{item.name}}"
        value: "{{item.value}}"
        region: "us-east-1"
      loop:
        - {name: "param.dev.catalogue.MONGO", value: "true"}
        - {name: "param.dev.catalogue.MONGO_ENDPOINT", value: "dev-mongodb.ransroboshop.online"}
        - {name: "param.dev.catalogue.MONGO_URL", value: "mongodb://dev-mongodb.ransroboshop.online:27017/catalogue"}
        - {name: "param.dev.user.MONGO", value: "true"}
        - {name: "param.dev.frontend.CATALOGUE_URL", value: "http://dev-catalogue.ransroboshop.online:8080/"}
        - {name: "param.dev.frontend.USER_URL", value: "http://dev-user.ransroboshop.online:8080/"}
        - {name: "param.dev.frontend.CART_URL", value: "http://dev-cart.ransroboshop.online:8080/"}
        - {name: "param.dev.frontend.SHIPPING_URL", value: "http://dev-shipping.ransroboshop.online:8080/"}
        - {name: "param.dev.frontend.PAYMENT_URL", value: "http://dev-payment.ransroboshop.online:8080/"}
        - {name: "param.dev.user.MONGO", value: "true"}
        - {name: "param.dev.user.MONGO_ENDPOINT", value: "dev-mongodb.ransroboshop.online"}
        - {name: "param.dev.user.MONGO_URL", value: "mongodb://dev-mongodb.ransroboshop.online:27017/users"}
        - {name: "param.dev.user.REDIS_HOST", value: "dev-redis.ransroboshop.online"}
        - {name: "param.dev.cart.REDIS_HOST", value: "dev-redis.ransroboshop.online"}
        - {name: "param.dev.cart.CATALOGUE_HOST", value: "dev-catalogue.ransroboshop.online"}
        - {name: "param.dev.cart.CATALOGUE_PORT", value: "8080"}
        - {name: "param.dev.mysql.ROOT_PASSWORD", value: "RoboShop@1"}



